### ISSUE TITLE
Android 7.0 "libjpeg.so" not found

### ISSUE THREAD

**Issue by gavinYip** [blueberryCoder/Compress#4]
FATAL EXCEPTION: Thread-5
                                                                        Process: com.blueberry.compress, PID: 14240
                                                                        java.lang.UnsatisfiedLinkError: dlopen failed: library "libjpeg.so" not found
                                                                            at java.lang.Runtime.loadLibrary0(Runtime.java:977)
                                                                            at java.lang.System.loadLibrary(System.java:1567)
                                                                            at com.blueberry.compress.ImageCompress.<clinit>(ImageCompress.java:12)
                                                                            at com.blueberry.compress.ImageCompress.nativeCompressBitmap(Native Method)
                                                                            at com.blueberry.compress.MainActivity.compressing(MainActivity.java:145)
                                                                            at com.blueberry.compress.MainActivity.access$400(MainActivity.java:29)
                                                                            at com.blueberry.compress.MainActivity$2.run(MainActivity.java:121)

**Comment by gavinYip** [comment]
sourceSets {
        main {
            java.srcDirs 'src/java'
            jniLibs.srcDirs '../libjpeg/prebuilt', 'libs'
            //  jni.srcDirs = ['src/cpp']
//            jniLibs.srcDirs '../libjpeg/prebuilt', 'libs'
            // 这里没有添加libjpeg.so这个动态库，也是可以执行的。
            // 原因在于android本身使用了 libjpeg.so这个动态库，
            // 这个库存放在/system/lib下，如果我们没有加入
            // libjpeg.so的话，他会去/system/lib下加载这个动态库

            // 如果android手机上没有 libjpeg.so这个动态库的话，
            // 也可以使用: jniLibs.srcDirs '../libjpeg/prebuilt' 'lib'
            // 将libjpeg.so加入到apk中
        }
    }
这么配置也没效果

**Comment by webbrain-one** [comment]
Hi! I opened PR [blueberryCoder/Compress#6](https://github.com/blueberryCoder/Compress/pull/6) to fix the Android 7.0 crash caused by the missing `libjpeg.so` native library. It should prevent the `UnsatisfiedLinkError` when calling `ImageCompress`.
